<?php 

/**
 * Supporting functions.
 */


/**
 * Sends an e-mail.
 *
 * @param array $form_values
 *   An array of values from the contact form fields that were submitted.
 *   There are just two relevant items: $form_values['email'] and
 *   $form_values['message'].
 */


function emailsystem_mail_send($form_values) {

	$module = 'emailsystem';
	$key = 'contact_message';

	$to= $form_values['email'];
	$from = variable_get('site_mail', 'systemdevcloud@live.co.uk');

	$params = $form_values;

	$language = language_default();

	$send = TRUE;


	$result = drupal_mail($module, $key, $to, $language, $params, $from, $send);



	// email logic 

	if($result['result'] == TRUE) {

		drupal_set_message(t('Your message has been sent'));

	}
	else {
		drupal_set_message(t('Your message has been refused'));
	}




}

/**
 * Implements hook_menu().
 *
 * Set up a page with an e-mail contact form on it.
 */

function emailsystem_menu() {
	

	$items['email'] = array(
    'title' => 'Contact form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emailsystem_form'),
    'access arguments' => array('access content'),

	);

	return $items;
}

/**
 * Implements hook_form().
 *
 * This creates the form
 */

function emailsystem_form() {

	$form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail address'),
    '#required' => TRUE,
	);

	$form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#required' => TRUE,
	);

	$form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit')
	);

	return $form;
}

/**
 * Implements hook_validate().
 *
 * This creates the form
 */

/**
 * Validation handler for email
 *
 * @param array $form
 *   The $form is an associatve array of form elements.
 * @param array $form_state
 *   The $form_state is a associatve array.
 */

function emailsystem_form_validate($form, &$form_state) {

if (!valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t('That e-mail address is not valid.'));
  }


}

/**
 *  Submit handler for email
 *
 * @param array $form
 *   The $form is an associatve array of form elements.
 * @param array $form_state
 *   The $form_state is a associatve array.
 */
function emailsystem_form_submit($form, &$form_state) {
  emailsystem_mail_send($form_state['values']);
}