<?php 

/**
 * Supporting functions.
 */

/**
 * Implements hook_menu().
 *
 * Set up a page with an e-mail contact form on it.
 */

function emailsystem_menu() {
	

	$items['email'] = array(
    'title' => 'Contact form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emailsystem_form'),
    'access arguments' => array('access content'),

	);

	return $items;
}

/**
 * Implements hook_form().
 *
 * This creates the form
 */

function emailsystem_form() {

	$form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail address'),
    '#required' => TRUE,
	);

	$form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#required' => TRUE,
	);

	$form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit')
	);

	return $form;
}

/**
 * Implements hook_validate().
 *
 * This creates the form
 */

/**
 * Validation handler for email
 *
 * @param array $form
 *   The $form is an associatve array of form elements.
 * @param array $form_state
 *   The $form_state is a associatve array.
 */

function emailsystem_form_validate($form, &$form_state) {

if (!valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t('That e-mail address is not valid.'));
  }


}

/**
 *  Submit handler for email
 *
 * @param array $form
 *   The $form is an associatve array of form elements.
 * @param array $form_state
 *   The $form_state is a associatve array.
 */
function emailsystem_form_submit($form, &$form_state) {
  drupal_set_message("email submitted");
}